h2non/pook

README.rst
Just a minor fix for the first **pook** usage example in the _README.rst_
=> fix README example

pook/activate_async.py, pook/api.py
If you apply `pook.activate` on `async def` function you will get `RuntimeWarning: coroutine 'xxx' was never awaited` with this patch you can use `pook.activate` on `async def` functions without any warnings.
an example:
```python
@pook.activate
async def test_anything():
url = 'http://google.com/'
pook.get(url, reply=200, response_body='...')
no_problem = await actual_method_that_do_http_request()
assert True == no_problem
```
=> Add activate_async decorator

requirements.txt, setup.py
Considering first example from the README:
```python
import pook
import requests
@pook.on
def test_my_api():
mock = pook.get('http://twitter.com/api/1/foobar', reply=404, response_json={'error': 'not found'})
resp = requests.get('http://twitter.com/api/1/foobar')
assert resp.status_code == 404
assert resp.json() == {"error": "not found"}
assert mock.calls == 1
test_my_api()
```
Running it under Python 2.7.* results in the following traceback:
```
Traceback (most recent call last):
File "example1.py", line 1, in <module>
import pook
File "/usr/local/var/pyenv/versions/pook-py27/lib/python2.7/site-packages/pook/__init__.py", line 1, in <module>
from .api import *  # noqa
File "/usr/local/var/pyenv/versions/pook-py27/lib/python2.7/site-packages/pook/api.py", line 5, in <module>
from .engine …
```
=> Fix py27 compatibility

pook/assertion.py
`assertRegexpMatches` has been deprecated in Python 3.3 in favor of `assertRegex`
=> replace depracated assertRegexpMatches with assertRegex

pook/mock.py, tests/unit/mock_test.py
Not sure if this is a bug, so this PR is trying to start a discussion.
It looks like this `or` check will always ignore the later part since `self._response` is never None (from __init__ it'll at least get default value `Response()`.
The proposed solution is: If `reply` is called, then Mock should always use provided args to be response instead of checking with `_response`.
My use case is, I have a callback function that use `reply` to modify the response dynamically. Maybe there's a better way to do that.
Thank you!
=> Always use overwritten response

requirements.txt
furl and jsonschema packages have been updated many revisions since 0.5 and 2.5 respectively, they are currently at 2.1 and 3.0. The requirements in this package forces a downgrade to these packages if the newer packages are already installed. This PR changes the requirements to be a "greater than" as to not force downgrades in an environment if the newer versions are already present.
Since  both furl and jsonschema are used with many conda (Anaconda) base installations this would happen frequently.
=> update requirements for furl and jsonschema

pook/engine.py, tests/unit/engine_test.py
As mentioned in issue #58, `enable_network` was not working when passing in a hostname. I have fixed the TypeError being raised, by extending the `network_filters` list in `use_network_filters` instead of the + concatenation that was being used.
=> Fix TypeError in use_network_filters by extending list with tuple

pook/headers.py
Starting in python 3.7 the following warning appears when importing from collections and not collections.abc, with the statement that it will no longer work in Python 3.8. This PR fixes the import to work across all python3 versions:
```
/usr/local/anaconda3/envs/prod/lib/python3.7/site-packages/pook/headers.py:2: 
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Mapping, MutableMapping
```
=> fix collections import warning

docs/examples.rst, examples/urllib3_chunked_response.py, pook/interceptors/urllib3.py, pook/response.py, tests/unit/interceptors/urllib3_test.py
This PR extends `pook`'s API to allow configuring a chunked response (only supported for `urllib3`).
Example:
```
import pook
import urllib3
with pook.use():
(pook.get('httpbin.org/chunky')
.reply(200)
.body(['returned', 'as', 'chunks'], chunked=True))
http = urllib3.PoolManager()
r = http.request('GET', 'httpbin.org/chunky')
print('Chunks:', list(r.read_chunked()))
```
=> Mocking chunked responses

pook/interceptors/aiohttp.py, requirements-dev.txt
We had two issues, params didn't make it through with the example call:
``` python
async with aiohttp.ClientSession(loop=loop) as session:
async with session.get(
url, params={'foo': 'bar'},
) as r:
```
and the latest version of aiohttp changed some interface patterns.
This is a quick hack to get `aiohttp==3.6.2` working.  I expect changes to be requested, but I wanted to open the PR to get some feedback on the changes so far.
Fixes https://github.com/h2non/pook/issues/56
=> Fix latest aiohttp

pook/interceptors/urllib3.py, tests/unit/interceptors/urllib3_test.py
The `urllib3` interceptor is never really disabled - see the committed unit test.
My assumption is that this is because of the two patches - the native one and the `requests` one presumably point to the same function. When the first mock is created it points to the original, while at the time of creation of the second mock, it will the point to the already mocked version.
The fix is to stop the mocks in reverse order.
=> fix(urllib3): interceptor is never really disabled

docs/examples.rst, examples/query_params_matching.py, tests/integration/pook_requests_test.py, tests/unit/mock_test.py
Hi,
Thank you for your marvelous library, it saved a lot of hours in testing different integrations 🤩
However, the documentation misses examples regarding matching query parameters.
Have spent some time to figure our that it should be declared in the next way 
```python
pook.get("https://google.com").params({"q": "I need coffee"})
```
but throws an exception, if pass it as a keyword parameter
```python
pook.get("https://google.com", params={"q": "Nooooo!"})
```
So, I would like to contribute a bit to the project by adding tests and examples to the documentation. 
Hope it will save time for another developer 🍸
=> Add examples and tests for matching query params

pook/interceptors/urllib3.py, tests/unit/interceptors/urllib3_test.py
Don't put non-strings into http header dict.
Closes #86
=> urllib3 v2+ support

pook/headers.py, pook/matchers/headers.py, tests/unit/matchers/headers_test.py
Fixes #50.
Rather than assuming everything is utf-8, which would lead to needing to still somehow handle the case where field values aren't decodable, we can rely on the HTTP spec, which says that header field values should be ASCII, and if not, to treat them as arbitrary data. Luckily, Python's `unicode_escape` encoding is able to handle these cases well enough without obscuring binary field data if we used something else, like base 64, to encode binary field values as strings.
The need to cast everything to a string comes from `HTTPHeaderDict` correctly handling multi-value header fields by rendering them as all the values joined together by commas. This matches the specification's directions for interpreting multi-value header fields, and so is desirable. However, there needs to be …
=> Handle binary header field values

requirements.txt
The constraints I added in #92 does not make sense. Reverting those changes for now and I'll use less rigid versions in a follow up.
=> Revert unnecessary dependencies upgrade

tests/unit/interceptors/urllib3_test.py
This will make the test fail if the mock hasn't matched (in the original PR it failed for other reason, earlier, not because of a mock mismatch).
By using https://httpbin.org/foo instead of https://example.com, the `resp.status` will be 404 instead of 200 if the mock didn't apply successfully. That's a less confusing failure mode.
=> More reliable test_post_with_headers

pook/assertion.py, pook/headers.py, pook/matchers/headers.py, pook/regex.py, tests/unit/matchers/headers_test.py
Fixes #96.
Adds new unit tests to reproduce the issue in the first commit, then fixes them in the subsequent commit. I also added more tests to cover other aspects of the headers matcher that were not tested before and fixed an issue I found with using `"re/.../"` formatted strings and actual compiled regex patterns as values in the headers.
In a future PR I'd like to add tests for each matcher type.
=> fix(regex): Fix usage of regex values in header matchers

pyproject.toml, tests/integration/examples_test.py
Made possible by https://github.com/mindflayer/python-mocket/pull/211
=> Enable mocket tests for >3.10

README.rst, pyproject.toml, src/pook/interceptors/__init__.py, src/pook/interceptors/_httpx.py, tests/unit/interceptors/httpx_test.py
Closes #71.
HTTPX documentation is here: https://www.python-httpx.org/
The current implementation supports everything, except HTTP2.
At first, I tried to implement this on the httpcore level, figuring that it'd be nice to go ahead and support anything that depended on httpcore. I still think that would be a good way to approach this, perhaps even supplanting the httpx-specific approach. However, httpcore's connection interfaces are significantly more complex to mock, if only because whereas httpx has only two entrypoints, httpcore technically has 8, an HTTP1, HTTP1.1 and HTTP2, and a connection pool connection for both sync and async requests (luckily all the supported proxy request types are implemented over top the other four and wouldn't require their own interceptors). Additionally, …
=> Add HTTPX support

src/pook/helpers.py, src/pook/mock.py, src/pook/request.py, src/pook/response.py, tests/unit/mock_test.py
Fixes #104 by using an explicit order to trigger methods on `Mock`.
This does not handle the case where query param arguments are passed without `url` at all. That will continue to raise an exception, which is intentional until a bigger change can be made to make the mock lazy and self-validating.
=> Fix `Mock` constructor params/url order mishandling

src/pook/matchers/api.py, src/pook/matchers/base.py, src/pook/matchers/headers.py, src/pook/matchers/query.py, src/pook/mock.py, src/pook/request.py, tests/unit/matchers/headers_test.py, tests/unit/matchers/query_test.py, tests/unit/mock_engine_test.py, tests/unit/mock_test.py
Fixes #110.
This PR simplifies the header and query param existence matches by introducing a new base matcher class, `ExistsMatcher`. Two new matcher classes, `HeaderExistsMatcher` and `QueryParameterExistsMatcher` are also introduced and the existing `header(s)_present` and `param_exists` methods are updated to use these matchers.
This removes the need to use the catch-all regexes for the value-check of the existence matchers. The new query-parameter existence matcher can be configured to allow empty values, which fixes #110 while preserving the existing behaviour of requiring _some_ value for the matcher's default behaviour. This prevents breaking backwards compatibility in the default behaviour. Setting `allow_empty=True` makes it possible to successfully match requests like …
=> Optionally match empty values in query parameter presence matcher

src/pook/interceptors/_httpx.py, tests/unit/interceptors/httpx_test.py
Closes #122.
Credit where credit's due, as was the case of https://github.com/h2non/pook/pull/91 this PR is also inspired by work done in https://github.com/Colin-b/pytest_httpx, the proposed fix corresponding to https://github.com/Colin-b/pytest_httpx/blob/b91bae4ec02a35e692700356dfe3753a20e32fc8/pytest_httpx/_httpx_mock.py#L269-L275
=> fix #122: httpx streaming via `iter_raw` raises `httpx.StreamConsumed`

History.rst, pyproject.toml, src/pook/__init__.py, src/pook/interceptors/_httpx.py, src/pook/interceptors/base.py, tests/unit/interceptors/aiohttp_test.py, tests/unit/interceptors/base.py, tests/unit/interceptors/httpx_test.py, tests/unit/interceptors/module_test.py, tests/unit/interceptors/urllib3_test.py, tests/unit/interceptors/urllib_test.py, tests/unit/matchers/query_test.py, tests/unit/mock_engine_test.py
Fixes https://github.com/h2non/pook/issues/125
Co-authored-by: vincbo <84619931+vincbo@users.noreply.github.com>
Kudos @vincbo for sharing the fix in the original issue.
I've wanted to add a suite of "standard" tests to run against each supported interceptor for a while. This PR adds that, in a minimal fashion, that will need to be expanded on, both to cover all the standard functionality for each supported HTTP client, and to create implementations for all explicitly supported clients. I only added implementations for the standard tests class for the clients that already had explicit tests.
=> Fix httpx incorrectly named method on interceptor subclass

pyproject.toml, src/pook/engine.py, src/pook/exceptions.py, src/pook/matcher.py, src/pook/mock.py, src/pook/regex.py, tests/integration/examples_test.py, tests/unit/exceptions_test.py, tests/unit/mock_test.py
Closes #127 by @silverwind
Thanks for the idea! If you have time to check out this PR and see if it matches what you had in mind, please do. Here's an example from a test case to demonstrate how this looks in practice:
```
__________________________________________________________________________________________ test_times_integrated ___________________________________________________________________________________________
httpbin = <pytest_httpbin.serve.Server object at 0x73b353b25640>
@pytest.mark.pook
def test_times_integrated(httpbin):
url = f"{httpbin.url}/status/404"
pook.get(url).times(2).reply(200).body("hello from pook")
res = urlopen(url)
assert res.read() == "hello from pook"
res = urlopen(url)
assert res.read() == "hello from pook"
>       urlopen(url) …
```
=> Expose expired mocks that would otherwise match the request

History.rst, src/pook/api.py, src/pook/interceptors/http.py, src/pook/interceptors/urllib3.py, src/pook/mock.py, src/pook/response.py, tests/conftest.py, tests/unit/interceptors/aiohttp_test.py, tests/unit/interceptors/base.py, tests/unit/interceptors/httpx_test.py, tests/unit/interceptors/urllib3_test.py, tests/unit/interceptors/urllib_test.py, tests/unit/mock_test.py, tests/unit/warnings_test.py
Implements the deprecation warning described in #128.
The PR is still a draft as it needs release notes.
=> Deprecate non-binary bodies

History.rst, examples/pytest_example.py, pyproject.toml, src/pook/pytest_fixture.py
I've been copy-pasting this simple fixture around in several project's `conftest.py` files for years now. I've seen the recent `pytest-pook` plugin on PyPI/sourcehut, but it doesn't actually have what is the most pytest-thonic usage, simply with a fixture and not needing to import the pook module from your test code at all:
```
def test_something(pook):
pook.get("https://example.org/").reply(204)
res = requests.get("https://example.org/")
assert res.status_code == 204
```
And I see no reason why this entrypoint couldn't just go into `pook` directly, rather than an extra package. It needn't create a pytest dependency because the submodule `pytest_fixture.py` is not imported except by pytest configure.
Let me know what you think!
=> Add a pytest fixture for pook

src/pook/interceptors/aiohttp.py, tests/unit/interceptors/aiohttp_test.py
The current implementation of the `aiohttp` interceptor does not account for using the `json` argument.
Before this PR you would get the following error when using the `json` param from aiohttp
with the JSONMatcher:
```
def no_matches(self, msg):
"""Raise `PookNoMatches` and reduce pytest printed stacktrace noise"""
>       raise PookNoMatches(msg)
E       pook.exceptions.PookNoMatches: pook error!
E       
E       => Cannot match any mock for the following request:
E       ==================================================
E       Method: POST
E       URL: http://example.com
E       ==================================================
E       
E       => Detailed matching errors:
E       JSONMatcher: 'NoneType' object has no attribute 'decode'
```
=> Improve aiohttp JSONMatcher support

.github/workflows/ci_cd.yml, .pre-commit-config.yaml, README.rst, pyproject.toml, src/pook/__init__.py, src/pook/interceptors/_httpx.py, src/pook/interceptors/aiohttp.py, src/pook/interceptors/http.py, src/pook/interceptors/urllib3.py, src/pook/request.py
This PR adds mypy and baseline type-checking infrastructure to CI and the project's scripts.
For this PR, type checking is restricted to the interceptors, and follow-up PRs can add annotations and checking to other files individually. I've done this to prevent the size of this PR from getting out of hand.
When adding annotations to a previously unannotated file, we'll add that file (or directory, if possible) to the `types` script's list of explicit places to check. After we've annotated all of `src/pook`, we can condense the list down to just that. Finally, we'll enable type checking for the tests.
Ideally, the addition of annotations does _not_ require introducing runtime code changes. At times, though, it seems like it will be, if the types are to be useful for Pook itself (rather than …
=> Add baseline for types

src/pook/activate_async.py, src/pook/api.py, tests/unit/api_test.py
This PL is for this [issue](https://github.com/h2non/pook/issues/144)
=> call pook.off in the end of pook.activate wrapper function

.github/workflows/ci_cd.yml, README.rst, docs/api.rst, docs/conf.py, docs/faq.rst, docs/how_it_works.rst, docs/install.rst, pyproject.toml, src/pook/request.py, src/pook/response.py
=> Improve docs build and fix warnings

.github/pull_request_template.md, History.rst, src/pook/interceptors/aiohttp.py, src/pook/interceptors/http.py, tests/unit/interceptors/aiohttp_test.py, tests/unit/interceptors/base.py, tests/unit/interceptors/httpx_test.py, tests/unit/interceptors/urllib3_test.py, tests/unit/interceptors/urllib_test.py
Fixes #151
Fixes #153
Also adds header tests to `StandardTests` and an implementation of that suite for `requests`. Previously, Pook relied on `urllib3` tests, which is probably fine, but ultimately an implementation detail of `requests` that is not strictly necessary (though really unlikely to change at this point).
=> Return the correct `headers` type for mocked urllib responses

src/pook/engine.py, tests/unit/interceptors/base.py
`enable_network` is currently broken for more than one hostname.
The documentation (https://github.com/h2non/pook/blob/master/src/pook/engine.py#L91-L92) says :
> _If **at least one** hostname matches with the outgoing traffic, the request will be executed via the real network._
Currently, it tries to match **all** hostnames.
=> Match any network filter instead of all

History.rst, src/pook/__init__.py, src/pook/interceptors/aiohttp.py, tests/integration/examples_test.py, tests/unit/interceptors/aiohttp_test.py
Fixes #156 
Also fixed a few aiohttp edge cases:
- If the client session has a special response class set, pook will now use that for the mocked response.
- Pook now uses aiohttp's named tuple to set the `version` on the response rather than an anonymous tuple.
=> Fix aiohttp session match

History.rst, pyproject.toml, src/pook/__init__.py, src/pook/interceptors/aiohttp.py, tests/unit/interceptors/aiohttp_test.py, tests/unit/interceptors/base.py
Follow up to #156 and the PR #157. The code in that PR overrides the Pook request headers with any headers sent from the aiohttp request. If you tried to match on headers configured via the session and the request, only the request headers would be present on the Pook request.
=> Ensure aiohttp headers matchable from both session and request

examples/regex.py, pyproject.toml, tests/conftest.py, tests/integration/engines/pytest_suite.py, tests/integration/examples_test.py, tests/unit/interceptors/aiohttp_test.py, tests/unit/interceptors/base.py, tests/unit/interceptors/httpx_test.py, tests/unit/interceptors/urllib3_test.py, tests/unit/matchers/query_test.py, tests/unit/mock_engine_test.py, tests/unit/mock_test.py
Fix #159 by removing httpbin and replacing it with a minimal version of a status-echo server in Falcon. This is sufficient for pook's testing needs. Additional functionality can be added to the `local_responder` as needed.
=> Replace pytest-httpbin with minimal Falcon version
